# Generated by Django 5.2.4 on 2025-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Asosiy Sahifa'), ('biz_haqimizda', 'Biz Haqimizda'), ('ochiq_malumotlar', "Ochiq Ma'lumotlar"), ('manzil', 'Manzil'), ('aloqa', 'Aloqa')], max_length=50, unique=True, verbose_name='Sahifa turi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Sahifa kontenti (Umumiy)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name="Sarlavha (Ochiq ma'lumotlar uchun)")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Tavsif (Ochiq ma'lumotlar uchun)")),
                ('file', models.FileField(blank=True, null=True, upload_to='page_files/', verbose_name="Fayl (Ochiq ma'lumotlar uchun)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/', verbose_name="Rasm (Ochiq ma'lumotlar uchun)")),
                ('company_info', models.TextField(blank=True, null=True, verbose_name="Kompaniya haqida ma'lumot (Biz Haqimizda uchun)")),
            ],
            options={
                'verbose_name': 'Sahifa kontenti',
                'verbose_name_plural': 'Sahifa kontentlari',
            },
        ),
    ]
