# Generated by Django 5.2.4 on 2025-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OchiqMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Ma'lumot sarlavhasi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqacha tavsif')),
                ('file', models.FileField(upload_to='ochiq_malumotlar_files/', verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ochiq_malumotlar_images/', verbose_name="Rasm (Agar bo'lsa)")),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
            ],
            options={
                'verbose_name': "Ochiq Ma'lumot",
                'verbose_name_plural': "Ochiq Ma'lumotlar",
                'ordering': ['-published_date'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Tavsif (Agar kerak bo'lsa)"),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='page_files/', verbose_name="Fayl (Agar kerak bo'lsa)"),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/', verbose_name="Rasm (Agar kerak bo'lsa)"),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_type',
            field=models.CharField(choices=[('home', 'Asosiy Sahifa'), ('biz_haqimizda', 'Biz Haqimizda'), ('ochiq_malumotlar_sahifasi', "Ochiq Ma'lumotlar Sahifasi (Umumiy)"), ('manzil', 'Manzil'), ('aloqa', 'Aloqa')], max_length=50, unique=True, verbose_name='Sahifa turi'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Sarlavha (Agar kerak bo'lsa)"),
        ),
    ]
